language: ruby
rvm:
- 2.2.6
env:
  global:
    secure: KlWBULVc5UeccnQLqL/IwTD7OZCC4MHj2ljvFK0CopYBw0mavF3p/iP8YD3Aeuwr70WAhtxPCs/ASUoUDBVC0yXPixwe+IlTY3iviY+4WnY9ArtS3efBzDGi3bQv43awtkWyQ4053VwgPAmRVuUyppDCGYp9hdUslM66tr044oU=
