---
ssl_validation: false

# only needed if you want to use this in a bosh release
#message_bus_servers:
#- nats://nats:nats@127.0.0.1:4222
#
#ip: 127.0.0.1
#port: 80
#external_host: p-cs.bosh-lite.com

catalog:
  services:
  - bindable: true
    description: An S3-compatible open source storage built on top of Ceph (Rados gateway).
    id: 33d2eeb0-0236-4c83-b494-da3faeb5b2e8
    metadata:
      displayName: S3-Ceph
      documentationUrl: https://github.com/orange-cloudfoundry/cf-s3-ceph-broker
      imageUrl: http://docs.ceph.com/docs/giant/_static/logo.png
      longDescription: Provisioning the service creates a Ceph bucket through Rados gateway. Binding an
        application creates unique credentials for that application to access the bucket.
      providerDisplayName: S3-Ceph
      supportUrl: https://github.com/orange-cloudfoundry/cf-s3-ceph-broker/issues
    name: s3-ceph
    plans:
    - description: A bucket on Ceph (Rados gateway).
      id: 946ce484-376b-41b4-8c4e-4bc830676115
      metadata:
        bullets:
        - Buckets are private
        costs:
        - amount:
            usd: 0.0
          unit: MONTHLY
        displayName: Bucket
      name: unlimited
    tags:
    - blobstore
    - s3
    - ceph
    - radosgw

syslog_progname: vcap.riak-cs-broker
